// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ_l5gdN5GQkTjVfpGQiku2B5yUMtr9Xs',
    appId: '1:174110307514:web:96a5b1face6d1fd544fe83',
    messagingSenderId: '174110307514',
    projectId: 'attendance-2fc3b',
    authDomain: 'attendance-2fc3b.firebaseapp.com',
    storageBucket: 'attendance-2fc3b.firebasestorage.app',
    measurementId: 'G-GBCE52W07W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApGXmFqBrFmDBta3WRQU4lufdPpcJUq1M',
    appId: '1:174110307514:android:87c2f10b4796513c44fe83',
    messagingSenderId: '174110307514',
    projectId: 'attendance-2fc3b',
    storageBucket: 'attendance-2fc3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKVlHfQQrSWun-8CbkQ65fMabf84tyG2Q',
    appId: '1:174110307514:ios:5d90b02793ee123044fe83',
    messagingSenderId: '174110307514',
    projectId: 'attendance-2fc3b',
    storageBucket: 'attendance-2fc3b.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKVlHfQQrSWun-8CbkQ65fMabf84tyG2Q',
    appId: '1:174110307514:ios:5d90b02793ee123044fe83',
    messagingSenderId: '174110307514',
    projectId: 'attendance-2fc3b',
    storageBucket: 'attendance-2fc3b.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ_l5gdN5GQkTjVfpGQiku2B5yUMtr9Xs',
    appId: '1:174110307514:web:33e54b648517152044fe83',
    messagingSenderId: '174110307514',
    projectId: 'attendance-2fc3b',
    authDomain: 'attendance-2fc3b.firebaseapp.com',
    storageBucket: 'attendance-2fc3b.firebasestorage.app',
    measurementId: 'G-ZD76WG8PN7',
  );

}